### ISSUE TITLE
Benchmark code is wrong

### ISSUE THREAD

**Issue by goccy** [WillAbides/rjson#25]
The following benchmark code is wrong .
https://github.com/WillAbides/rjson/blob/main/benchmarks/goccyjson.go#L24

Must fix package from `encoding/json` to `goccy/go-json` and update result on README.md

**Comment by WillAbides** [comment]
Thanks!  I can't believe I didn't notice that before. I thought it was very suspicious that go-json's performance seemed the same as "encoding/json".  I'm fixing it now.

**Comment by WillAbides** [comment]
I've corrected the code and I did a quick run of the benchmark script with just rjson and go-json and updated README.md with that.  It takes a while to do a full run, and I didn't want the mistake to be online any longer than necessary. Later today I will do a full run and update again.

I apologize for making a mistake that is unfavorable to your code. go-json is a great package.

**Comment by goccy** [comment]
No problem 😃  Thank you for the correction !
